### ISSUE TITLE
Any way to add new tags or allow arbitrary tags?

### ISSUE THREAD

**Issue by bcooney** [dn5/vicilog#2]
I can't see where the tags are pulling from, but it would be great to be able to add tags as the project needs, or to just allow arbitrary tags (where anything between 2 brackets would become a tag, color randomized). Thanks for this tool, btw. Really enjoy using it.

**Comment by duraki** [comment]
The tags are pulled from JSON file attached to project directory and then regex matched inside rel.js.  

Dirty hack:
- Line 49 in rel.js (add regex match, for e.g. "todo"):
- `.match(/^\[(new|fixed|improved|removed|added|todo)\]\s(.*)/i);`  
- Add style in your index:
- `.change-todo { background-color: #000000 }`  

Someone might give it a try and implement it by default for e.g. ask for `--newtag todo`. I'm currently busy cus of Christmas but development should continue in January.

**Comment by bcooney** [comment]
I'll give it a try. Thanks a lot for pointing me in the right direction!

**Comment by duraki** [comment]
:+1:
