### ISSUE TITLE
[Feature Request] Categorization?

### ISSUE THREAD

**Issue by CyberSecGuy** [dn5/vicilog#4]
I love this application, and for quick notes it's great, however there's no real Categorization. I plan on using this as a quick and easy way to generate human readable release notes for a video game.

Suggestion: Allow categorization at the start of your "Insert changelog data" section through the use of Hashtag/Pound symbol to declare a split and creation of a category.

_**For example; this:**_

```
Insert your changelog data (Hint: use a tags; e.g. [improved]):
• [new] General#Created a new way to track server changes. They will be displayed here.
• [fixed] Towny#Fixed permissions issue with Towny, preventing abuse. Contact us if you're missing Perms.
• [added] Towny#Updated towny from 0.91.0.2 to 0.91.1.0 - a significant update.
• [removed] Website#Removed website Staff Tools, in place of Change Log(this).
• [improved] Economy#Lowered price of Stone to $10.00 from $150.00
end
```

_**Would end up looking like this:**_

> ## General:
> 
> [ New ] Created a new way to track server changes. They will be displayed here.
> ## Website:
> 
> [ New ] Removed website Staff Tools, in place of Change Log(this).
> ## Towny:
> 
> [ Fix ] Fixed permissions issue with Towny, preventing abuse. Contact us if you're missing Perms.
> [ Improved ] Updated towny from 0.91.0.2 to 0.91.1.0 - a significant update.
> ## Economy:
> 
> [ Improved ] Lowered price of Stone to $10.00 from $150.00

Thus, you could add large amounts of "Changes" and have them format and categorize neatly, regardless of the initial order.

**Comment by CyberSecGuy** [comment]
Just an idea, I'd love to hear you feedback, thanks so much!

**Comment by duraki** [comment]
I though about this but eventually dropped it out since parsing of the data is in real time this could be counter-efficient. You may as well use a string identifier through version specification (e.g. Version 2.0 / General) and such.  

Hope it helps. This is out of the scope for a vicilog.
